from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QPushButton


class Ui_graphdesign(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 10, 661, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.label.setAlignment(Qt.AlignCenter)
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 10, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 60, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 110, 91, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 160, 91, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 210, 91, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 260, 91, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(70, 310, 91, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(70, 460, 91, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(70, 410, 91, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(70, 360, 91, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(70, 510, 91, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(70, 610, 91, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(70, 560, 91, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(770, 660, 91, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(210, 660, 91, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(400, 660, 91, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(590, 660, 91, 41))
        self.pushButton_17.setObjectName("pushButton_14")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.select_button_clicked)
        self.pushButton_2.clicked.connect(self.on_zoomout_clicked)
        self.pushButton_3.clicked.connect(self.on_zoomin_clicked)
        self.pushButton_4.clicked.connect(self.left_rotate)
        self.pushButton_5.clicked.connect(self.right_rotate)
        self.pushButton_6.clicked.connect(self.to_gray)
        self.pushButton_7.clicked.connect(self.filter)
        self.pushButton_8.clicked.connect(self.image_hist_demo)
        self.pushButton_9.clicked.connect(self.morph)
        self.pushButton_10.clicked.connect(self.jiangzao)
        self.pushButton_11.clicked.connect(self.gammacorrect)
        self.pushButton_12.clicked.connect(self.edgetest)
        self.pushButton_13.clicked.connect(self.gradtest)
        self.pushButton_14.clicked.connect(self.resetgraph)
        self.pushButton_15.clicked.connect(self.histogram)
        self.pushButton_16.clicked.connect(self.call_back_action_close_func)
        self.pushButton_17.clicked.connect(self.call_back_action_store_func)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片编辑"))
        self.label.setText(_translate("MainWindow", "请选择图片！"))
        self.pushButton.setText(_translate("MainWindow", "打开图片"))
        self.pushButton_2.setText(_translate("MainWindow", "放大"))
        self.pushButton_3.setText(_translate("MainWindow", "缩小"))
        self.pushButton_4.setText(_translate("MainWindow", "左旋"))
        self.pushButton_5.setText(_translate("MainWindow", "右旋"))
        self.pushButton_6.setText(_translate("MainWindow", "灰度图"))
        self.pushButton_7.setText(_translate("MainWindow", "平滑处理"))
        self.pushButton_8.setText(_translate("MainWindow", "亮度调节"))
        self.pushButton_9.setText(_translate("MainWindow", "形态学"))
        self.pushButton_10.setText(_translate("MainWindow", "卷积降噪"))
        self.pushButton_11.setText(_translate("MainWindow", "伽马校正"))
        self.pushButton_12.setText(_translate("MainWindow", "边缘检测"))
        self.pushButton_13.setText(_translate("MainWindow", "图像梯度"))
        self.pushButton_14.setText(_translate("MainWindow", "恢复原图"))
        self.pushButton_15.setText(_translate("MainWindow", "查看直方图"))
        self.pushButton_16.setText(_translate("MainWindow", "退出"))
        self.pushButton_17.setText(_translate("MainWindow", "保存图片"))
